// @author: claude | phase: pixiv-tool | manifest
import type { ToolManifest } from '../../core/types';

export const manifest: ToolManifest = {
  id: 'pixiv-downloader',
  name: 'Pixiv下载',
  description: 'Pixiv 画师作品下载与同步',
  category: 'download',
  version: '2.0.0',
  icon: 'download',
  tags: ['pixiv', 'download', 'illust', 'ugoira', 'novel', 'sync'],
  hasSettings: true,
  defaultSettings: {
    pythonPath: 'python',
    localSavePath: '',
    dbPath: './db/pixiv_manager.db',
    logDir: './logs',
    tempPath: './temp',
    avatarsPath: './avatars',
    storageMode: 'local',
    nasIp: '',
    nasUser: '',
    nasPass: '',
    nasShare: '',
    nasBasePath: 'PIXIV',
    nasRemoteName: '',
    sftpHost: '',
    sftpPort: 22,
    sftpUser: '',
    sftpPass: '',
    sftpPrivateKey: '',
    sftpBasePath: 'PIXIV',
    ftpHost: '',
    ftpPort: 21,
    ftpUser: '',
    ftpPass: '',
    ftpBasePath: 'PIXIV',
    ftpTls: false,
    webdavUrl: '',
    webdavUser: '',
    webdavPass: '',
    webdavBasePath: 'PIXIV',
    s3Endpoint: '',
    s3Region: '',
    s3Bucket: '',
    s3AccessKey: '',
    s3SecretKey: '',
    s3Prefix: 'PIXIV',
    s3ForcePathStyle: true,
    downloadThreads: 4,
    mainAccountSyncThreads: 1,
    backupAccountSyncThreads: 2,
    mainAccountDownloadThreads: 1,
    backupAccountDownloadThreads: 2,
    metadataRefreshLimit: 20,
    ugoiraOutput: 'gif',
    rateLimitEnabled: true,
    autoThrottleEnabled: true,
    failureRateThreshold: 0.5,
  },
};
